//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demos {
    using System;
    using System.Collections;
    
    
    public sealed class Employee {
        
        private int idField;
        
        private string nameField;
        
        public Employee() {
        }
        
        public Employee(string name) {
            nameField = name;
            nameField = name;
        }
        
        public int EmployeeId {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        public string SayHelloTo(string name) {
            return "Hello " + name +", my name is" + Name;
        }
    }
}
